// Generated by `cargo xtask gen-ts` from protocol and strategy schemas. Do not edit by hand.

type ProfileCatalog_ProxyHopProfile = {
  "credentialRef": string;
  "host": string;
  "hostKey": string;
  "port"?: number;
  "username": string;
};
type ProfileCatalog_TargetProfile = {
  "boardId"?: string | null;
  "credentialRef": string;
  "deviceId"?: string | null;
  "host": string;
  "hostKey"?: string | null;
  "keepaliveSeconds"?: number;
  "port"?: number;
  "proxyChain"?: Array<ProfileCatalog_ProxyHopProfile>;
  "socId"?: string | null;
  "username": string;
};
export type ProfileCatalog = Record<string, ProfileCatalog_TargetProfile>;

type TargetProfile_ProxyHopProfile = {
  "credentialRef": string;
  "host": string;
  "hostKey": string;
  "port"?: number;
  "username": string;
};
export type TargetProfile = {
  "boardId"?: string | null;
  "credentialRef": string;
  "deviceId"?: string | null;
  "host": string;
  "hostKey"?: string | null;
  "keepaliveSeconds"?: number;
  "port"?: number;
  "proxyChain"?: Array<TargetProfile_ProxyHopProfile>;
  "socId"?: string | null;
  "username": string;
};

export type ProxyHopProfile = {
  "credentialRef": string;
  "host": string;
  "hostKey": string;
  "port"?: number;
  "username": string;
};

type TargetOverrides_ProxyHopProfile = {
  "credentialRef": string;
  "host": string;
  "hostKey": string;
  "port"?: number;
  "username": string;
};
export type TargetOverrides = {
  "boardId"?: string | null;
  "credentialRef"?: string | null;
  "deviceId"?: string | null;
  "host"?: string | null;
  "hostKey"?: string | null;
  "keepaliveSeconds"?: number | null;
  "port"?: number | null;
  "profile"?: string | null;
  "proxyChain"?: Array<TargetOverrides_ProxyHopProfile> | null;
  "socId"?: string | null;
  "username"?: string | null;
};

type CredentialSecrets_CredentialMaterial = {
  "passphrase"?: CredentialSecrets_SensitiveString | null;
  "password"?: CredentialSecrets_SensitiveString | null;
};
type CredentialSecrets_SensitiveString = string;
export type CredentialSecrets = Record<string, CredentialSecrets_CredentialMaterial>;

export type SensitiveString = string;

export type HardwareDescriptor = {
  "boardId"?: string | null;
  "boardRevision"?: string | null;
  "deviceId"?: string | null;
  "model"?: string | null;
  "protocolVersion"?: number | null;
  "socId"?: string | null;
};

type VerifiedTargetIdentity_HardwareDescriptor = {
  "boardId"?: string | null;
  "boardRevision"?: string | null;
  "deviceId"?: string | null;
  "model"?: string | null;
  "protocolVersion"?: number | null;
  "socId"?: string | null;
};
export type VerifiedTargetIdentity = {
  "descriptor": VerifiedTargetIdentity_HardwareDescriptor;
  "host": string;
  "hostKeyFingerprint": string;
  "port": number;
};

type RpcError_RpcErrorData = {
  "code": string;
  "detail"?: string | null;
  "phase": string;
  "remediation": string;
  "retriable": boolean;
  "targetState"?: string | null;
};
export type RpcError = {
  "code": number;
  "data"?: RpcError_RpcErrorData | null;
  "message": string;
};

export type RpcErrorData = {
  "code": string;
  "detail"?: string | null;
  "phase": string;
  "remediation": string;
  "retriable": boolean;
  "targetState"?: string | null;
};

export type ArtifactRecord = {
  "configuration"?: string | null;
  "contentHash": string;
  "path": string;
  "size": number;
  "symbolsPath"?: string | null;
  "targetName": string;
};

export type InitializeParams = {
  "capabilities"?: Array<string>;
  "frontend": string;
  "protocolVersion": string;
};

export type InitializeResult = {
  "capabilities": Array<string>;
  "coreVersion": string;
  "protocolVersion": string;
};

export type EmptyParams = Record<string, never>;

export type PingResult = {
  "pong": boolean;
};

export type ConnectionState = "disconnected" | "connecting" | "attached" | "reconnecting";

type ResolveProfileParams_ProfileCatalog = Record<string, ResolveProfileParams_TargetProfile>;
type ResolveProfileParams_ProxyHopProfile = {
  "credentialRef": string;
  "host": string;
  "hostKey": string;
  "port"?: number;
  "username": string;
};
type ResolveProfileParams_TargetOverrides = {
  "boardId"?: string | null;
  "credentialRef"?: string | null;
  "deviceId"?: string | null;
  "host"?: string | null;
  "hostKey"?: string | null;
  "keepaliveSeconds"?: number | null;
  "port"?: number | null;
  "profile"?: string | null;
  "proxyChain"?: Array<ResolveProfileParams_ProxyHopProfile> | null;
  "socId"?: string | null;
  "username"?: string | null;
};
type ResolveProfileParams_TargetProfile = {
  "boardId"?: string | null;
  "credentialRef": string;
  "deviceId"?: string | null;
  "host": string;
  "hostKey"?: string | null;
  "keepaliveSeconds"?: number;
  "port"?: number;
  "proxyChain"?: Array<ResolveProfileParams_ProxyHopProfile>;
  "socId"?: string | null;
  "username": string;
};
export type ResolveProfileParams = {
  "catalog": ResolveProfileParams_ProfileCatalog;
  "target": ResolveProfileParams_TargetOverrides;
};

export type ResolvedProfile = {
  "boardId"?: string | null;
  "deviceId"?: string | null;
  "host": string;
  "hostKeyPinned": boolean;
  "keepaliveSeconds": number;
  "port": number;
  "profileName"?: string | null;
  "proxyHops": number;
  "socId"?: string | null;
  "username": string;
};

type ResolveProfileResult_ResolvedProfile = {
  "boardId"?: string | null;
  "deviceId"?: string | null;
  "host": string;
  "hostKeyPinned": boolean;
  "keepaliveSeconds": number;
  "port": number;
  "profileName"?: string | null;
  "proxyHops": number;
  "socId"?: string | null;
  "username": string;
};
export type ResolveProfileResult = {
  "profile": ResolveProfileResult_ResolvedProfile;
};

type InspectHostKeyParams_ProfileCatalog = Record<string, InspectHostKeyParams_TargetProfile>;
type InspectHostKeyParams_ProxyHopProfile = {
  "credentialRef": string;
  "host": string;
  "hostKey": string;
  "port"?: number;
  "username": string;
};
type InspectHostKeyParams_TargetOverrides = {
  "boardId"?: string | null;
  "credentialRef"?: string | null;
  "deviceId"?: string | null;
  "host"?: string | null;
  "hostKey"?: string | null;
  "keepaliveSeconds"?: number | null;
  "port"?: number | null;
  "profile"?: string | null;
  "proxyChain"?: Array<InspectHostKeyParams_ProxyHopProfile> | null;
  "socId"?: string | null;
  "username"?: string | null;
};
type InspectHostKeyParams_TargetProfile = {
  "boardId"?: string | null;
  "credentialRef": string;
  "deviceId"?: string | null;
  "host": string;
  "hostKey"?: string | null;
  "keepaliveSeconds"?: number;
  "port"?: number;
  "proxyChain"?: Array<InspectHostKeyParams_ProxyHopProfile>;
  "socId"?: string | null;
  "username": string;
};
export type InspectHostKeyParams = {
  "catalog": InspectHostKeyParams_ProfileCatalog;
  "target": InspectHostKeyParams_TargetOverrides;
};

export type InspectHostKeyResult = {
  "hostKeyFingerprint": string;
};

type AttachRequest_CredentialMaterial = {
  "passphrase"?: AttachRequest_SensitiveString | null;
  "password"?: AttachRequest_SensitiveString | null;
};
type AttachRequest_CredentialSecrets = Record<string, AttachRequest_CredentialMaterial>;
type AttachRequest_ProfileCatalog = Record<string, AttachRequest_TargetProfile>;
type AttachRequest_ProxyHopProfile = {
  "credentialRef": string;
  "host": string;
  "hostKey": string;
  "port"?: number;
  "username": string;
};
type AttachRequest_SensitiveString = string;
type AttachRequest_TargetOverrides = {
  "boardId"?: string | null;
  "credentialRef"?: string | null;
  "deviceId"?: string | null;
  "host"?: string | null;
  "hostKey"?: string | null;
  "keepaliveSeconds"?: number | null;
  "port"?: number | null;
  "profile"?: string | null;
  "proxyChain"?: Array<AttachRequest_ProxyHopProfile> | null;
  "socId"?: string | null;
  "username"?: string | null;
};
type AttachRequest_TargetProfile = {
  "boardId"?: string | null;
  "credentialRef": string;
  "deviceId"?: string | null;
  "host": string;
  "hostKey"?: string | null;
  "keepaliveSeconds"?: number;
  "port"?: number;
  "proxyChain"?: Array<AttachRequest_ProxyHopProfile>;
  "socId"?: string | null;
  "username": string;
};
export type AttachRequest = {
  "catalog": AttachRequest_ProfileCatalog;
  "credentialSecrets"?: AttachRequest_CredentialSecrets | null;
  "strategyConfiguration"?: unknown;
  "strategyId": string;
  "target": AttachRequest_TargetOverrides;
};

export type TargetOperation = "deploy" | "start" | "stop" | "restart" | "restorePrevious" | "logs" | "debugPrepare";

type AttachResult_ConnectionState = "disconnected" | "connecting" | "attached" | "reconnecting";
type AttachResult_HardwareDescriptor = {
  "boardId"?: string | null;
  "boardRevision"?: string | null;
  "deviceId"?: string | null;
  "model"?: string | null;
  "protocolVersion"?: number | null;
  "socId"?: string | null;
};
type AttachResult_ResolvedProfile = {
  "boardId"?: string | null;
  "deviceId"?: string | null;
  "host": string;
  "hostKeyPinned": boolean;
  "keepaliveSeconds": number;
  "port": number;
  "profileName"?: string | null;
  "proxyHops": number;
  "socId"?: string | null;
  "username": string;
};
type AttachResult_TargetOperation = "deploy" | "start" | "stop" | "restart" | "restorePrevious" | "logs" | "debugPrepare";
type AttachResult_VerifiedTargetIdentity = {
  "descriptor": AttachResult_HardwareDescriptor;
  "host": string;
  "hostKeyFingerprint": string;
  "port": number;
};
export type AttachResult = {
  "attachId": string;
  "identity": AttachResult_VerifiedTargetIdentity;
  "operations": Array<AttachResult_TargetOperation>;
  "profile": AttachResult_ResolvedProfile;
  "state": AttachResult_ConnectionState;
  "strategyId": string;
};

export type AttachRef = {
  "attachId": string;
};

type DisconnectResult_ConnectionState = "disconnected" | "connecting" | "attached" | "reconnecting";
export type DisconnectResult = {
  "state": DisconnectResult_ConnectionState;
};

type ArtifactHandoffParams_ArtifactRecord = {
  "configuration"?: string | null;
  "contentHash": string;
  "path": string;
  "size": number;
  "symbolsPath"?: string | null;
  "targetName": string;
};
export type ArtifactHandoffParams = {
  "artifact": ArtifactHandoffParams_ArtifactRecord;
  "attachId": string;
};

export type ArtifactHandoffResult = {
  "accepted": boolean;
};

export type OperationResult = {
  "operationId": string;
};

export type LogsParams = {
  "attachId": string;
  "cursor"?: string | null;
  "maxBytes"?: number;
};

export type OutputStream = "stdout" | "stderr";

type OutputChunk_OutputStream = "stdout" | "stderr";
export type OutputChunk = {
  "bytes": Array<number>;
  "stream": OutputChunk_OutputStream;
};

type LogsResult_OutputChunk = {
  "bytes": Array<number>;
  "stream": LogsResult_OutputStream;
};
type LogsResult_OutputStream = "stdout" | "stderr";
export type LogsResult = {
  "chunks": Array<LogsResult_OutputChunk>;
  "nextCursor"?: string | null;
};

type InspectResult_ConnectionState = "disconnected" | "connecting" | "attached" | "reconnecting";
type InspectResult_HardwareDescriptor = {
  "boardId"?: string | null;
  "boardRevision"?: string | null;
  "deviceId"?: string | null;
  "model"?: string | null;
  "protocolVersion"?: number | null;
  "socId"?: string | null;
};
type InspectResult_TargetOperation = "deploy" | "start" | "stop" | "restart" | "restorePrevious" | "logs" | "debugPrepare";
type InspectResult_VerifiedTargetIdentity = {
  "descriptor": InspectResult_HardwareDescriptor;
  "host": string;
  "hostKeyFingerprint": string;
  "port": number;
};
export type InspectResult = {
  "identity"?: InspectResult_VerifiedTargetIdentity | null;
  "operations": Array<InspectResult_TargetOperation>;
  "state": InspectResult_ConnectionState;
  "targetState"?: string | null;
};

export type DebugPrepareResult = {
  "host": string;
  "port": number;
  "program"?: string | null;
  "providerId": string;
  "symbolsPath"?: string | null;
};

export type ProgressToken = string | number;

type CancelParams_ProgressToken = string | number;
export type CancelParams = {
  "id": CancelParams_ProgressToken;
};

type ProgressParams_ProgressToken = string | number;
type ProgressParams_ProgressValue = {
  "cancellable"?: boolean | null;
  "kind": "begin";
  "message"?: string | null;
  "percentage"?: number | null;
  "title": string;
} | {
  "kind": "report";
  "message"?: string | null;
  "percentage"?: number | null;
} | {
  "kind": "end";
  "message"?: string | null;
};
export type ProgressParams = {
  "token": ProgressParams_ProgressToken;
  "value": ProgressParams_ProgressValue;
};

export type ProgressValue = {
  "cancellable"?: boolean | null;
  "kind": "begin";
  "message"?: string | null;
  "percentage"?: number | null;
  "title": string;
} | {
  "kind": "report";
  "message"?: string | null;
  "percentage"?: number | null;
} | {
  "kind": "end";
  "message"?: string | null;
};

type ConnectionStateParams_ConnectionState = "disconnected" | "connecting" | "attached" | "reconnecting";
export type ConnectionStateParams = {
  "attachId": string;
  "detail"?: string | null;
  "state": ConnectionStateParams_ConnectionState;
};

export type TargetStateParams = {
  "attachId": string;
  "detail"?: string | null;
  "state": string;
};

type OutputParams_OutputStream = "stdout" | "stderr";
export type OutputParams = {
  "attachId": string;
  "bytes": Array<number>;
  "stream": OutputParams_OutputStream;
};

type ErrorParams_ProgressToken = string | number;
type ErrorParams_RpcError = {
  "code": number;
  "data"?: ErrorParams_RpcErrorData | null;
  "message": string;
};
type ErrorParams_RpcErrorData = {
  "code": string;
  "detail"?: string | null;
  "phase": string;
  "remediation": string;
  "retriable": boolean;
  "targetState"?: string | null;
};
export type ErrorParams = {
  "error": ErrorParams_RpcError;
  "requestId"?: ErrorParams_ProgressToken | null;
};

// Strategy configuration: linux.remoteproc
export type LinuxRemoteprocConfiguration = {
  "firmwarePath": string;
  "instance": string;
};

export const PROTOCOL_VERSION = "0.1.0";
export const MAX_MESSAGE_BYTES = 16777216;

export const REQUEST_METHODS = [
  "betelgeuz/initialize",
  "betelgeuz/shutdown",
  "betelgeuz/ping",
  "betelgeuz/resolveProfile",
  "betelgeuz/inspectHostKey",
  "betelgeuz/attach",
  "betelgeuz/disconnect",
  "betelgeuz/artifactHandoff",
  "betelgeuz/deploy",
  "betelgeuz/start",
  "betelgeuz/stop",
  "betelgeuz/restart",
  "betelgeuz/logs",
  "betelgeuz/inspect",
  "betelgeuz/debugPrepare",
  "betelgeuz/restorePrevious",
] as const;

export type RequestMethod = typeof REQUEST_METHODS[number];

export const NOTIFICATION_METHODS = [
  "$/cancelRequest",
  "betelgeuz/connectionState",
  "betelgeuz/targetState",
  "$/progress",
  "betelgeuz/output",
  "betelgeuz/error",
] as const;

export type NotificationMethod = typeof NOTIFICATION_METHODS[number];

export type RpcRequestParams = {
  "betelgeuz/initialize": InitializeParams;
  "betelgeuz/shutdown": EmptyParams;
  "betelgeuz/ping": EmptyParams;
  "betelgeuz/resolveProfile": ResolveProfileParams;
  "betelgeuz/inspectHostKey": InspectHostKeyParams;
  "betelgeuz/attach": AttachRequest;
  "betelgeuz/disconnect": AttachRef;
  "betelgeuz/artifactHandoff": ArtifactHandoffParams;
  "betelgeuz/deploy": AttachRef;
  "betelgeuz/start": AttachRef;
  "betelgeuz/stop": AttachRef;
  "betelgeuz/restart": AttachRef;
  "betelgeuz/logs": LogsParams;
  "betelgeuz/inspect": AttachRef;
  "betelgeuz/debugPrepare": AttachRef;
  "betelgeuz/restorePrevious": AttachRef;
};

export type RpcRequestResults = {
  "betelgeuz/initialize": InitializeResult;
  "betelgeuz/shutdown": null;
  "betelgeuz/ping": PingResult;
  "betelgeuz/resolveProfile": ResolveProfileResult;
  "betelgeuz/inspectHostKey": InspectHostKeyResult;
  "betelgeuz/attach": AttachResult;
  "betelgeuz/disconnect": DisconnectResult;
  "betelgeuz/artifactHandoff": ArtifactHandoffResult;
  "betelgeuz/deploy": OperationResult;
  "betelgeuz/start": OperationResult;
  "betelgeuz/stop": OperationResult;
  "betelgeuz/restart": OperationResult;
  "betelgeuz/logs": LogsResult;
  "betelgeuz/inspect": InspectResult;
  "betelgeuz/debugPrepare": DebugPrepareResult;
  "betelgeuz/restorePrevious": OperationResult;
};

export type RpcNotificationParams = {
  "$/cancelRequest": CancelParams;
  "betelgeuz/connectionState": ConnectionStateParams;
  "betelgeuz/targetState": TargetStateParams;
  "$/progress": ProgressParams;
  "betelgeuz/output": OutputParams;
  "betelgeuz/error": ErrorParams;
};
