//! `cargo xtask` — codegen and packaging, keeping every generated artifact
//! derived from the `protocol` crate instead of hand-maintained.

use std::path::PathBuf;

fn main() {
    let task = std::env::args().nth(1).unwrap_or_default();
    match task.as_str() {
        // JSON Schema for the protocol, configuration keys, and descriptor.
        "gen-schema" => todo_task("gen-schema"),
        // docs/ERRORS.md from the error catalog enum.
        "gen-errors" => gen_errors(),
        // TypeScript types for the VS Code adapter from the schema.
        "gen-ts" => todo_task("gen-ts"),
        // Build core binaries and assemble the extension VSIX.
        "package" => todo_task("package"),
        _ => {
            eprintln!("usage: cargo xtask <gen-schema|gen-errors|gen-ts|package>");
            std::process::exit(2);
        }
    }
}

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask lives at the workspace root")
        .to_path_buf()
}

/// `docs/ERRORS.md` from the catalog in `crates/protocol`. Never hand-edited.
fn gen_errors() {
    use protocol::error::ErrorCode;

    let mut out = String::new();
    out.push_str("# Error catalog\n\n");
    out.push_str(
        "Generated by `cargo xtask gen-errors` from the catalog in `crates/protocol/src/error.rs`. Do not edit by hand.\n\n",
    );
    out.push_str("| code | phase | meaning | remediation | retriable |\n");
    out.push_str("| --- | --- | --- | --- | --- |\n");
    for code in ErrorCode::ALL {
        let def = code.def();
        let phase = def.phase.map(|p| p.as_str()).unwrap_or("any");
        let retriable = if def.retriable { "yes" } else { "no" };
        out.push_str(&format!(
            "| `{}` | {} | {} | {} | {} |\n",
            code.code(),
            phase,
            def.summary,
            def.remediation.as_str(),
            retriable
        ));
    }

    let path = workspace_root().join("docs").join("ERRORS.md");
    std::fs::write(&path, out).expect("write docs/ERRORS.md");
    println!("wrote {}", path.display());
}

fn todo_task(name: &str) -> ! {
    eprintln!("xtask {name}: not implemented yet (Phase 0)");
    std::process::exit(1);
}
