//! `cargo xtask` — codegen and packaging, keeping every generated artifact
//! derived from their owning crates instead of hand-maintained.

use std::path::PathBuf;

fn main() {
    let task = std::env::args().nth(1).unwrap_or_default();
    match task.as_str() {
        // JSON Schema for the protocol, configuration keys, and descriptor.
        "gen-schema" => todo_task("gen-schema"),
        // docs/ERRORS.md from common and strategy error definitions.
        "gen-errors" => gen_errors(),
        // TypeScript types for the VS Code adapter from the schema.
        "gen-ts" => todo_task("gen-ts"),
        // Build core binaries and assemble the extension VSIX.
        "package" => todo_task("package"),
        _ => {
            eprintln!("usage: cargo xtask <gen-schema|gen-errors|gen-ts|package>");
            std::process::exit(2);
        }
    }
}

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask lives at the workspace root")
        .to_path_buf()
}

/// `docs/ERRORS.md` from the common and strategy-owned catalogs. Never hand-edited.
fn gen_errors() {
    use std::collections::HashSet;
    use errors::{ErrorCatalogEntry, ErrorCode};

    let mut out = String::new();
    out.push_str("# Error catalog\n\n");
    out.push_str(
        "Generated by `cargo xtask gen-errors` from core and strategy error definitions. Do not edit by hand. Remediation values are stable action identifiers for frontend presentation.\n\n",
    );
    out.push_str("| code | phase | meaning | remediation action | retriable |\n");
    out.push_str("| --- | --- | --- | --- | --- |\n");
    let mut catalog: Vec<ErrorCatalogEntry> = ErrorCode::ALL
        .into_iter()
        .map(|code| ErrorCatalogEntry {
            code: code.code(),
            definition: code.def(),
        })
        .collect();
    catalog.extend_from_slice(strategy::ERROR_CATALOG);
    let mut seen = HashSet::new();
    for entry in catalog {
        assert!(
            seen.insert(entry.code),
            "duplicate error code: {}",
            entry.code
        );
        let def = entry.definition;
        let phase = def.phase.map(|p| p.as_str()).unwrap_or("any");
        let retriable = if def.retriable { "yes" } else { "no" };
        out.push_str(&format!(
            "| `{}` | {} | {} | `{}` | {} |\n",
            entry.code,
            phase,
            def.summary,
            def.remediation,
            retriable
        ));
    }

    let path = workspace_root().join("docs").join("ERRORS.md");
    std::fs::write(&path, out).expect("write docs/ERRORS.md");
    println!("wrote {}", path.display());
}

fn todo_task(name: &str) -> ! {
    eprintln!("xtask {name}: not implemented yet (Phase 0)");
    std::process::exit(1);
}
