//! `cargo xtask` — codegen and packaging, keeping every generated artifact
//! derived from their owning crates instead of hand-maintained.

use std::path::PathBuf;

fn main() {
    let mut args = std::env::args().skip(1);
    let task = args.next().unwrap_or_default();
    let check_generated = args.any(|arg| arg == "--check");
    match task.as_str() {
        // JSON Schema for the protocol, configuration keys, and descriptor.
        "gen-schema" => gen_schema(check_generated),
        // docs/ERRORS.md from common and strategy error definitions.
        "gen-errors" => gen_errors(check_generated),
        // TypeScript types for the VS Code adapter from the protocol schemas.
        "gen-ts" => gen_ts(check_generated),
        // Build core binaries and assemble the extension VSIX.
        "package" => todo_task("package"),
        _ => {
            eprintln!("usage: cargo xtask <gen-schema|gen-errors|gen-ts|package>");
            std::process::exit(2);
        }
    }
}

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask lives at the workspace root")
        .to_path_buf()
}

/// JSON Schema and protocol reference derived from the protocol crate.
fn gen_schema(check: bool) {
    let root = workspace_root();
    let schema_dir = root.join("target").join("schema").join("protocol");
    std::fs::create_dir_all(&schema_dir).expect("create protocol schema directory");
    let schemas = protocol_schemas();
    validate_method_contracts(&schemas);
    for (name, schema) in &schemas {
        let path = schema_dir.join(format!("{name}.json"));
        let content = format!(
            "{}\n",
            serde_json::to_string_pretty(schema).expect("schema serializes")
        );
        write_generated(&path, &content, false);
    }

    let strategy_schema_dir = root.join("target").join("schema").join("strategies");
    std::fs::create_dir_all(&strategy_schema_dir).expect("create strategy schema directory");
    let strategy_schemas = strategy::builtin_config_schemas();
    for (id, schema) in &strategy_schemas {
        let path = strategy_schema_dir.join(format!("{id}.json"));
        let content = format!("{}\n", serde_json::to_string_pretty(schema).unwrap());
        write_generated(&path, &content, false);
    }

    let mut doc = String::from(
        "# Protocol reference\n\nGenerated by `cargo xtask gen-schema` from protocol and strategy contracts. Do not edit by hand.\n\n",
    );
    doc.push_str(&format!(
        "Protocol version: `{}`. Framing: JSON-RPC 2.0 with LSP-style `Content-Length` headers over stdio.\n\n",
        protocol::PROTOCOL_VERSION
    ));
    doc.push_str(&format!(
        "The maximum JSON body size is `{}` bytes. Artifact contents stay on the host; the artifact record carries a local path, target name, configuration, size, content hash, and optional symbols path; the core opens that path and streams it over SFTP.\n\n",
        protocol::MAX_MESSAGE_BYTES
    ));

    doc.push_str("## Requests\n\n| Method | Params | Result |\n| --- | --- | --- |\n");
    for contract in protocol::methods::METHOD_CONTRACTS {
        let result = contract.result.unwrap_or("none");
        doc.push_str(&format!(
            "| `{}` | `{}` | `{}` |\n",
            contract.method, contract.params, result
        ));
    }
    doc.push_str("\n## Notifications\n\n| Method | Params |\n| --- | --- |\n");
    for contract in protocol::methods::NOTIFICATION_CONTRACTS {
        doc.push_str(&format!(
            "| `{}` | `{}` |\n",
            contract.method, contract.params
        ));
    }
    doc.push_str("\n## Configuration keys\n\n| Key |\n| --- |\n");
    for key in protocol::config::FIXED_KEYS {
        doc.push_str(&format!("| `{key}` |\n"));
    }
    doc.push_str("\nPattern prefixes:\n\n");
    for pattern in protocol::config::KEY_PATTERNS {
        doc.push_str(&format!("- `{pattern}`\n"));
    }
    doc.push_str("\n## Strategy configuration\n\n");
    for key in strategy::CONFIG_KEYS {
        let full_key = protocol::config::strategy_key(key.strategy_id, key.name);
        doc.push_str(&format!("- `{full_key}`\n"));
    }
    doc.push_str("\nGenerated JSON Schemas are build artifacts under `target/schema/`, published only when a third-party frontend consumes them.\n");

    let doc_path = root.join("docs").join("protocol.md");
    write_generated(&doc_path, &doc, check);
    if check {
        println!("protocol schemas and reference are current");
    } else {
        println!(
            "wrote {} protocol schemas, {} strategy schemas, and {}",
            schemas.len(),
            strategy_schemas.len(),
            doc_path.display()
        );
    }
}

fn protocol_schemas() -> Vec<(&'static str, schemars::Schema)> {
    use protocol::{config, descriptor, error, methods};

    vec![
        (
            "profile-catalog",
            schemars::schema_for!(config::ProfileCatalog),
        ),
        (
            "target-profile",
            schemars::schema_for!(config::TargetProfile),
        ),
        (
            "proxy-hop-profile",
            schemars::schema_for!(config::ProxyHopProfile),
        ),
        (
            "target-overrides",
            schemars::schema_for!(config::TargetOverrides),
        ),
        (
            "credential-secrets",
            schemars::schema_for!(config::CredentialSecrets),
        ),
        (
            "sensitive-string",
            schemars::schema_for!(config::SensitiveString),
        ),
        (
            "hardware-descriptor",
            schemars::schema_for!(descriptor::HardwareDescriptor),
        ),
        (
            "verified-target-identity",
            schemars::schema_for!(descriptor::VerifiedTargetIdentity),
        ),
        ("rpc-error", schemars::schema_for!(error::RpcError)),
        ("rpc-error-data", schemars::schema_for!(error::RpcErrorData)),
        (
            "artifact-record",
            schemars::schema_for!(methods::ArtifactRecord),
        ),
        (
            "initialize-params",
            schemars::schema_for!(methods::InitializeParams),
        ),
        (
            "initialize-result",
            schemars::schema_for!(methods::InitializeResult),
        ),
        ("empty-params", schemars::schema_for!(methods::EmptyParams)),
        ("ping-result", schemars::schema_for!(methods::PingResult)),
        (
            "connection-state",
            schemars::schema_for!(methods::ConnectionState),
        ),
        (
            "resolve-profile-params",
            schemars::schema_for!(methods::ResolveProfileParams),
        ),
        (
            "resolved-profile",
            schemars::schema_for!(methods::ResolvedProfile),
        ),
        (
            "resolve-profile-result",
            schemars::schema_for!(methods::ResolveProfileResult),
        ),
        (
            "inspect-host-key-params",
            schemars::schema_for!(methods::InspectHostKeyParams),
        ),
        (
            "inspect-host-key-result",
            schemars::schema_for!(methods::InspectHostKeyResult),
        ),
        (
            "attach-request",
            schemars::schema_for!(methods::AttachRequest),
        ),
        (
            "target-operation",
            schemars::schema_for!(methods::TargetOperation),
        ),
        (
            "attach-result",
            schemars::schema_for!(methods::AttachResult),
        ),
        ("attach-ref", schemars::schema_for!(methods::AttachRef)),
        (
            "disconnect-result",
            schemars::schema_for!(methods::DisconnectResult),
        ),
        (
            "artifact-handoff-params",
            schemars::schema_for!(methods::ArtifactHandoffParams),
        ),
        (
            "artifact-handoff-result",
            schemars::schema_for!(methods::ArtifactHandoffResult),
        ),
        (
            "operation-result",
            schemars::schema_for!(methods::OperationResult),
        ),
        ("logs-params", schemars::schema_for!(methods::LogsParams)),
        (
            "output-stream",
            schemars::schema_for!(methods::OutputStream),
        ),
        ("output-chunk", schemars::schema_for!(methods::OutputChunk)),
        ("logs-result", schemars::schema_for!(methods::LogsResult)),
        (
            "inspect-result",
            schemars::schema_for!(methods::InspectResult),
        ),
        (
            "debug-prepare-result",
            schemars::schema_for!(methods::DebugPrepareResult),
        ),
        (
            "progress-token",
            schemars::schema_for!(methods::ProgressToken),
        ),
        (
            "cancel-params",
            schemars::schema_for!(methods::CancelParams),
        ),
        (
            "progress-params",
            schemars::schema_for!(methods::ProgressParams),
        ),
        (
            "progress-value",
            schemars::schema_for!(methods::ProgressValue),
        ),
        (
            "connection-state-params",
            schemars::schema_for!(methods::ConnectionStateParams),
        ),
        (
            "target-state-params",
            schemars::schema_for!(methods::TargetStateParams),
        ),
        (
            "output-params",
            schemars::schema_for!(methods::OutputParams),
        ),
        ("error-params", schemars::schema_for!(methods::ErrorParams)),
    ]
}

fn gen_ts(check: bool) {
    let schemas = protocol_schemas();
    validate_method_contracts(&schemas);
    let mut content = String::from(
        "// Generated by `cargo xtask gen-ts` from protocol and strategy schemas. Do not edit by hand.\n\n",
    );
    for (_, schema) in schemas {
        let schema = serde_json::to_value(schema).expect("schema converts to JSON");
        content.push_str(&typescript_schema(&schema));
        content.push('\n');
    }
    for (id, schema) in strategy::builtin_config_schemas() {
        content.push_str(&format!("// Strategy configuration: {id}\n"));
        content.push_str(&typescript_schema(&schema));
        content.push('\n');
    }

    content.push_str(&format!(
        "export const PROTOCOL_VERSION = {};\nexport const MAX_MESSAGE_BYTES = {};\n\n",
        serde_json::to_string(protocol::PROTOCOL_VERSION).unwrap(),
        protocol::MAX_MESSAGE_BYTES
    ));
    content.push_str("export const REQUEST_METHODS = [\n");
    for contract in protocol::methods::METHOD_CONTRACTS {
        content.push_str(&format!(
            "  {},\n",
            serde_json::to_string(contract.method).unwrap()
        ));
    }
    content
        .push_str("] as const;\n\nexport type RequestMethod = typeof REQUEST_METHODS[number];\n\n");

    content.push_str("export const NOTIFICATION_METHODS = [\n");
    for contract in protocol::methods::NOTIFICATION_CONTRACTS {
        content.push_str(&format!(
            "  {},\n",
            serde_json::to_string(contract.method).unwrap()
        ));
    }
    content.push_str(
        "] as const;\n\nexport type NotificationMethod = typeof NOTIFICATION_METHODS[number];\n\n",
    );

    content.push_str("export type RpcRequestParams = {\n");
    for contract in protocol::methods::METHOD_CONTRACTS {
        content.push_str(&format!(
            "  {}: {};\n",
            serde_json::to_string(contract.method).unwrap(),
            contract.params
        ));
    }
    content.push_str("};\n\nexport type RpcRequestResults = {\n");
    for contract in protocol::methods::METHOD_CONTRACTS {
        let result = contract.result.unwrap_or("never");
        content.push_str(&format!(
            "  {}: {};\n",
            serde_json::to_string(contract.method).unwrap(),
            if result == "null" { "null" } else { result }
        ));
    }
    content.push_str("};\n\nexport type RpcNotificationParams = {\n");
    for contract in protocol::methods::NOTIFICATION_CONTRACTS {
        content.push_str(&format!(
            "  {}: {};\n",
            serde_json::to_string(contract.method).unwrap(),
            contract.params
        ));
    }
    content.push_str("};\n");

    let path = workspace_root()
        .join("editors")
        .join("code")
        .join("src")
        .join("protocol.ts");
    write_generated(&path, &content, check);
    if check {
        println!("TypeScript protocol types are current");
    } else {
        println!("wrote {}", path.display());
    }
}

fn typescript_schema(schema: &serde_json::Value) -> String {
    let root_name = schema
        .get("title")
        .and_then(serde_json::Value::as_str)
        .map(type_identifier)
        .unwrap_or_else(|| "ProtocolType".into());
    let mut out = String::new();
    if let Some(definitions) = schema.get("$defs").and_then(serde_json::Value::as_object) {
        for (name, definition) in definitions {
            let local_name = format!("{root_name}_{}", type_identifier(name));
            out.push_str(&format!(
                "type {local_name} = {};\n",
                schema_type(definition, &root_name)
            ));
        }
    }
    out.push_str(&format!(
        "export type {root_name} = {};\n",
        schema_type(schema, &root_name)
    ));
    out
}

fn schema_type(schema: &serde_json::Value, scope: &str) -> String {
    use serde_json::Value;

    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        if let Some(name) = reference.strip_prefix("#/$defs/") {
            return format!("{scope}_{}", type_identifier(name));
        }
        return "unknown".into();
    }
    for key in ["oneOf", "anyOf", "allOf"] {
        if let Some(variants) = schema.get(key).and_then(Value::as_array) {
            let separator = if key == "allOf" { " & " } else { " | " };
            return variants
                .iter()
                .map(|variant| schema_type(variant, scope))
                .collect::<Vec<_>>()
                .join(separator);
        }
    }
    if let Some(value) = schema.get("const") {
        return serde_json::to_string(value).unwrap();
    }
    if let Some(values) = schema.get("enum").and_then(Value::as_array) {
        return values
            .iter()
            .map(|value| serde_json::to_string(value).unwrap())
            .collect::<Vec<_>>()
            .join(" | ");
    }
    if let Some(types) = schema.get("type").and_then(Value::as_array) {
        let variants = types
            .iter()
            .filter_map(Value::as_str)
            .map(|kind| {
                let mut branch = schema.clone();
                branch["type"] = Value::String(kind.to_owned());
                schema_type(&branch, scope)
            })
            .collect::<Vec<_>>();
        return variants.join(" | ");
    }

    match schema.get("type").and_then(Value::as_str) {
        Some("object") => {
            if let Some(properties) = schema.get("properties").and_then(Value::as_object) {
                let required: std::collections::HashSet<_> = schema
                    .get("required")
                    .and_then(Value::as_array)
                    .into_iter()
                    .flatten()
                    .filter_map(Value::as_str)
                    .collect();
                let mut fields = String::from("{\n");
                for (name, property) in properties {
                    let optional = if required.contains(name.as_str()) {
                        ""
                    } else {
                        "?"
                    };
                    fields.push_str(&format!(
                        "  {}{optional}: {};\n",
                        serde_json::to_string(name).unwrap(),
                        schema_type(property, scope)
                    ));
                }
                fields.push('}');
                fields
            } else if let Some(additional) = schema.get("additionalProperties") {
                if additional == false {
                    "Record<string, never>".into()
                } else if additional == true {
                    "Record<string, unknown>".into()
                } else {
                    format!("Record<string, {}>", schema_type(additional, scope))
                }
            } else {
                "Record<string, unknown>".into()
            }
        }
        Some("array") => {
            let item = schema
                .get("items")
                .map(|item| schema_type(item, scope))
                .unwrap_or_else(|| "unknown".into());
            format!("Array<{item}>")
        }
        Some("string") => "string".into(),
        Some("integer" | "number") => "number".into(),
        Some("boolean") => "boolean".into(),
        Some("null") => "null".into(),
        _ => "unknown".into(),
    }
}

fn type_identifier(value: &str) -> String {
    let mut result = String::new();
    for segment in value.split(|character: char| !character.is_ascii_alphanumeric()) {
        if segment.is_empty() {
            continue;
        }
        let mut characters = segment.chars();
        if let Some(first) = characters.next() {
            result.extend(first.to_uppercase());
            result.extend(characters);
        }
    }
    if result.is_empty() || result.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        format!("Type{result}")
    } else {
        result
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn typescript_generation_preserves_nullability_and_schema_references() {
        let schema = json!({
            "title": "Example",
            "$defs": { "Record": { "type": "object", "properties": { "ok": { "type": "boolean" } }, "required": ["ok"] } },
            "type": "object",
            "properties": {
                "value": { "type": ["string", "null"] },
                "record": { "$ref": "#/$defs/Record" }
            },
            "required": ["record"]
        });

        let output = typescript_schema(&schema);
        assert!(output.contains("type Example_Record ="));
        assert!(output.contains("\"value\"?: string | null;"));
        assert!(output.contains("\"record\": Example_Record;"));
        assert!(!output.contains("string | unknown"));
    }
}

fn validate_method_contracts(schemas: &[(&str, schemars::Schema)]) {
    let names: std::collections::HashSet<_> = schemas.iter().map(|(name, _)| *name).collect();
    for contract in protocol::methods::METHOD_CONTRACTS {
        assert!(
            names.contains(type_schema_name(contract.params).as_str()),
            "no JSON schema registered for {} params `{}`",
            contract.method,
            contract.params
        );
        if let Some(result) = contract.result.filter(|result| *result != "null") {
            assert!(
                names.contains(type_schema_name(result).as_str()),
                "no JSON schema registered for {} result `{result}`",
                contract.method
            );
        }
    }
    for contract in protocol::methods::NOTIFICATION_CONTRACTS {
        assert!(
            names.contains(type_schema_name(contract.params).as_str()),
            "no JSON schema registered for {} params `{}`",
            contract.method,
            contract.params
        );
    }
}

fn type_schema_name(type_name: &str) -> String {
    let mut result = String::new();
    for (index, character) in type_name.chars().enumerate() {
        if character.is_ascii_uppercase() && index > 0 {
            result.push('-');
        }
        result.push(character.to_ascii_lowercase());
    }
    result
}

fn write_generated(path: &std::path::Path, content: &str, check: bool) {
    if check {
        let existing = std::fs::read_to_string(path).unwrap_or_else(|error| {
            panic!("cannot read generated file {}: {error}", path.display())
        });
        assert_eq!(
            existing,
            content,
            "generated file is stale: {}",
            path.display()
        );
    } else {
        std::fs::write(path, content).unwrap_or_else(|error| {
            panic!("cannot write generated file {}: {error}", path.display())
        });
    }
}

/// `docs/ERRORS.md` from the common and strategy-owned catalogs. Never hand-edited.
fn gen_errors(check: bool) {
    use errors::{ErrorCatalogEntry, ErrorCode};
    use std::collections::HashSet;

    let mut out = String::new();
    out.push_str("# Error catalog\n\n");
    out.push_str(
        "Generated by `cargo xtask gen-errors` from core and strategy error definitions. Do not edit by hand. Remediation values are stable action identifiers for frontend presentation.\n\n",
    );
    out.push_str("| code | phase | meaning | remediation action | retriable |\n");
    out.push_str("| --- | --- | --- | --- | --- |\n");
    let mut catalog: Vec<ErrorCatalogEntry> = ErrorCode::ALL
        .into_iter()
        .map(|code| ErrorCatalogEntry {
            code: code.code(),
            definition: code.def(),
        })
        .collect();
    catalog.extend_from_slice(strategy::ERROR_CATALOG);
    let mut seen = HashSet::new();
    for entry in catalog {
        assert!(
            seen.insert(entry.code),
            "duplicate error code: {}",
            entry.code
        );
        let def = entry.definition;
        let phase = def.phase.map(|p| p.as_str()).unwrap_or("any");
        let retriable = if def.retriable { "yes" } else { "no" };
        out.push_str(&format!(
            "| `{}` | {} | {} | `{}` | {} |\n",
            entry.code, phase, def.summary, def.remediation, retriable
        ));
    }

    let path = workspace_root().join("docs").join("ERRORS.md");
    write_generated(&path, &out, check);
    if check {
        println!("error catalog is current");
    } else {
        println!("wrote {}", path.display());
    }
}

fn todo_task(name: &str) -> ! {
    eprintln!("xtask {name}: not implemented yet (Phase 0)");
    std::process::exit(1);
}
